version: '2'
services:
  app:
    image: gangs-proto-server:latest
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/gangs_server
    links:
      - postgres
    ports:
     - "4000:4000"
  postgres:
    image: postgres
    environment:
      - PGDATA=/dbdata
    volumes:
      - ./dbdata:/dbdata
    ports:
      - "5432:5432"
