version: '2'
services:
  app:
    build: .
    working_dir: /code
    environment:
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/gangs_server
    links:
      - postgres
    ports:
     - "4040:4040"
  postgres:
    image: postgres
    environment:
      - PGDATA=/dbdata
    volumes:
      - ./dbdata:/dbdata
    ports:
      - "5432:5432"
